volumes:
  media:
  pg_data:
  static:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: lenta4ka/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: lenta4ka/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: lenta4ka/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 7070:80
  